<a href="https://colab.research.google.com/github/Deshvan11/Data-Science/blob/main/Numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
l = [[1,2,3],[3,4,5],[5,6,7],[7,8,9]]
l

[[1, 2, 3], [3, 4, 5], [5, 6, 7], [7, 8, 9]]

In [ ]:
np.array(l)

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])

In [ ]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [ ]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [ ]:
arr = np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
arr = np.ones((4,8))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
arr = np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
np.random.rand(10)

array([0.55939984, 0.90109295, 0.69777903, 0.43100797, 0.44533544,
       0.98658566, 0.32619182, 0.14615743, 0.04320681, 0.98954829])

In [ ]:
np.random.randn(10)

array([ 1.26775777, -0.29005537, -0.51055759,  1.45562515,  1.35806796,
        0.53679906, -0.16813988,  1.07889198, -0.43991648, -1.38222484])

In [ ]:
np.random.randint(10,20,10)

array([17, 14, 15, 18, 11, 13, 18, 18, 11, 15])

In [ ]:
arr = np.array([[1,2,3],[3,4,5],[5,6,7],[7,8,9]])
arr

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])

In [ ]:
arr.shape #here shape is attribute

(4, 3)

In [ ]:
arr.size

12

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr.min()# here min is a function so we call it by '()'

np.int64(1)

In [ ]:
arr.max()

np.int64(9)

In [ ]:
arr.sum()

np.int64(60)

In [ ]:
np.sum(arr,axis = 1) # 0 for coloumn sum & 1 for row sum

array([ 6, 12, 18, 24])

In [ ]:
arr.mean()

np.float64(5.0)

In [ ]:
arr.std()

np.float64(2.3804761428476167)

In [ ]:
arr.argmax()

np.int64(11)

In [ ]:
arr.argmin()

np.int64(0)

In [ ]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

**NUMPY INDEXING AND SLICING OF VECTORS**

In [ ]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr_slice = arr[3::2] # [start:end:Arthmetic Progression]
arr_slice

array([14, 16, 18, 20])

In [ ]:
arr[4]

np.int64(15)

**NUMPY INDEXING AND SLICING OF MATRIX**

In [ ]:
arr = np.arange(1,31).reshape(6,5) #total no. element in 'arange' should match the no. of element in the 'matrix'
arr                                # [(1,31) = 30 elements) should be = [(6,5) = 30 elements]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
slice = arr[3: ,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

**BOOLEAN INDEXING**

In [ ]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
boolean_index = arr%2 ==0
boolean_index

array([ True,  True,  True,  True,  True])

In [ ]:
arr = arr[boolean_index]
arr

array([12, 14, 16, 18, 20])

**ARRAY OPERATIONS**

In [ ]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [ ]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [ ]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [ ]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [ ]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [ ]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

**BROADCASTING**

In [ ]:
l= [10,20,30,40,50]
arr= np.array(l)
arr

array([10, 20, 30, 40, 50])

In [ ]:
arr + 10 , arr + l

(array([20, 30, 40, 50, 60]), array([ 20,  40,  60,  80, 100]))

In [ ]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

** DEEP AND SHALLOW COPY**

In [ ]:
a = np.arange(1,21)
a
#A shallow copy creates a new compound object, but it populates this new object with references to the child objects found in the original.
#This means that if the original object contains mutable nested objects (like lists or dictionaries),
# both the original and the shallow copy will share references to these same nested objects.
#import copy
#original_list = [[1, 2], 3]
#shallow_copied_list = copy.copy(original_list)
#shallow_copied_list[0][0] = 99  # Modifying a nested mutable object
#print(original_list)          # Output: [[99, 2], 3] - original is affected'''

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
slice = a[:5]
slice = slice*10
slice
#A deep copy creates a new compound object and then recursively inserts copies of the child objects found in the original.
#This means that a deep copy creates a completely independent clone of the original object, including all nested objects within it
#import copy
#original_list = [[1, 2], 3]
#deep_copied_list = copy.deepcopy(original_list)
#deep_copied_list[0][0] = 99  # Modifying a nested mutable object
#print(original_list)        # Output: [[1, 2], 3] - original is not affected

array([10, 20, 30, 40, 50])

In [ ]:
a
b = a

In [ ]:
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
b = a.copy() #its a shallow copy which does a copy of array and if any changes are made in it it will not reflect on the original

In [ ]:
b[0]= 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

**MATRIC OPERATION**

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8 ]])

In [ ]:
A

array([[1, 2],
       [3, 4]])

In [ ]:
B

array([[5, 6],
       [7, 8]])

In [ ]:
A*B #it is simple multiplication

array([[ 5, 12],
       [21, 32]])

In [ ]:
A @ B # but the multiplication in matrix is different
#it should be
#[[first row(of 1st matrix)+ first column(of 2nd matrix)], [first row(of 1st matrix)+ second column(of 2nd matrix)]]
#[[second row(of 1st matrix)+ first column(of 2nd matrix)]],[second row(of 1st matrix)+ second column(of 2nd matrix)]

array([[19, 22],
       [43, 50]])

In [ ]:
#same goes for
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [ ]:
np.dot(B,A)

array([[23, 34],
       [31, 46]])

**ADVANCED ARRAY MANIPULATION**

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [ ]:
np.vstack((a,b)) # also called as np.rowsatck((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.hstack((a,b)) # also called as np.concatinate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

**SPLITTING ARRAY**

In [ ]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(c,1)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [ ]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [ ]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
a = np.vsplit(c,4)

In [ ]:
for i in a:
  print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
