<a href="https://colab.research.google.com/github/Deshvan11/Data-Science/blob/main/Numpy_exersises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Valid Sudoku**

In [ ]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

**General Questions**

In [ ]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [ ]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [ ]:
#Find the average age of students.
data.mean(axis=0)[0]

np.float64(18.4)

In [ ]:
#Extract Math marks of all students.
data[:,1]

array([85, 92, 76, 65, 90])

In [ ]:
#Find the highest Science mark.
data.max(axis=0)[2]

np.int64(95)

In [ ]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1]>90]

array([[19, 92, 88]])

In [ ]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [ ]:
#Increase Math marks of all students by 5.
data[:,1]+5

array([90, 97, 81, 70, 95])

In [ ]:
#Find how many students are younger than 19.
data[data[:,0]<19]

array([[18, 85, 78],
       [17, 76, 95],
       [18, 65, 70]])

In [ ]:
#Calculate the average marks in each subject (column-wise mean).
sci= data.mean(axis=0)[2]
math= data.mean(axis=0)[1]
print('sci :',sci)
print('math:',math)

sci : 83.2
math: 81.6


In [ ]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1]>80) & (data[:,2]>80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [ ]:
#Replace all Science marks < 75 with 0.
data[data[:,2]<75]=0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [ 0,  0,  0],
       [20, 90, 85]])